[package]
name = "rlua-derive-unofficial"
version = "0.1.0"
authors = ["Patrick Barrett <patrick.barrett@smartthings.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = "1"
quote = "1"
rlua = "0.16"
